# Generated by Django 2.1.5 on 2019-01-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190121_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrecipient',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
