# Generated by Django 2.1.7 on 2019-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190121_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftrecipient',
            name='id',
        ),
        migrations.AddField(
            model_name='giftrecipient',
            name='static_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
