# Generated by Django 2.1.7 on 2019-03-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190322_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftrecipient',
            name='static_id',
        ),
        migrations.AddField(
            model_name='giftrecipient',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
